# LEMUR Analysis Configuration File
# =================================
# Configuration parameters for GSE225158 snRNA-seq LEMUR analysis
# Edit these values to customize your analysis

# Analysis Information
analysis:
  name: "GSE225158_OUD_vs_Control_LEMUR"
  description: "LEMUR analysis of striatal snRNA-seq data comparing OUD vs Control"
  author: "Generated Analysis Pipeline"
  date: "2024"

# File Paths
paths:
  # Base directory (relative to script location)
  base_dir: "/Users/aumchampaneri/Complement-OUD/Multi-Omics Study"

  # Input H5AD file
  input_h5ad: "data/raw/snrna/GSE225158_BU_OUD_Striatum_refined_all_SeuratObj_N22.h5ad"

  # Output directory
  output_dir: "/Users/aumchampaneri/Complement-OUD/Multi-Omics Study/scripts/snrna/LEMUR Analysis/outputs"

  # Optional: Custom gene sets for enrichment
  gene_sets: null

# Metadata Configuration
metadata:
  # Required columns in colData
  batch_column: "donor_id"
  condition_column: "condition"

  # Expected condition levels
  conditions:
    control: "Control"
    treatment: "OUD"

  # Optional additional covariates
  covariates:
    - "Sex"
    - "Age" # if available

# Quality Control Parameters
quality_control:
  # Cell filtering thresholds
  cell_filters:
    min_genes: 200
    max_genes: 6000
    min_counts: 500
    max_counts: 50000
    max_mito_percent: 20
    max_ribo_percent: 50 # optional

  # Gene filtering
  gene_filters:
    min_cells: 10 # genes expressed in at least N cells

  # Mitochondrial gene patterns
  mito_patterns:
    - "^MT-"
    - "^mt-"

  # Ribosomal gene patterns
  ribo_patterns:
    - "^RP[SL]"
    - "^Rp[sl]"

# Normalization and Feature Selection
normalization:
  # Method for size factor calculation
  size_factor_method: "scran" # or "deconvolution"

  # Highly variable genes
  hvg:
    n_genes: 3000
    method: "modelGeneVar" # or "modelGeneVarByPoisson"

  # Log transformation
  log_transform: true
  pseudocount: 1

# Dimensionality Reduction
dimensionality_reduction:
  # PCA parameters
  pca:
    n_components: 50
    use_hvg_only: true

  # UMAP parameters
  umap:
    n_neighbors: 30
    min_dist: 0.3
    n_components: 2
    metric: "euclidean"
    from_pca: true
    n_pcs: 30

# LEMUR Model Parameters
lemur:
  # Core LEMUR settings
  n_embedding: 20
  design_formula: "~ donor_id + condition"

  # Advanced LEMUR parameters
  advanced:
    # Regularization
    ridge_penalty: 1e-4

    # Convergence criteria
    max_iter: 1000
    tolerance: 1e-6

    # Optimization
    optimizer: "L-BFGS-B"

    # Embedding initialization
    init_method: "pca" # or "random"

# Batch Correction
batch_correction:
  # Apply Harmony correction
  use_harmony: true

  # Harmony parameters
  harmony:
    theta: 2 # diversity clustering penalty
    lambda: 1 # ridge regression penalty
    sigma: 0.1 # width of soft kmeans clusters
    nclust: null # number of clusters (auto if null)
    tau: 0 # protection against overclustering
    block_size: 0.05 # proportion of cells to update per iteration
    max_iter_harmony: 10
    max_iter_cluster: 20
    epsilon_cluster: 1e-5
    epsilon_harmony: 1e-4

# Differential Expression Testing
differential_expression:
  # Statistical thresholds
  fdr_threshold: 0.05
  effect_size_threshold: 0.1

  # Contrasts to test
  contrasts:
    main_effect:
      name: "OUD_vs_Control"
      description: "Main effect of OUD vs Control"
      formula: "condition"

    # Optional: Additional contrasts
    # interaction_effect:
    #   name: "OUD_Sex_Interaction"
    #   description: "Interaction between OUD and Sex"
    #   formula: "condition:Sex"

# Neighborhood Analysis
neighborhoods:
  # Enable neighborhood detection
  enable: true

  # Parameters for neighborhood detection
  k_neighbors: 15
  resolution: 0.5
  min_neighborhood_size: 10

  # Embedding to use for neighborhoods
  embedding_source: "harmony" # "harmony" or "lemur"

# Visualization Parameters
visualization:
  # Figure settings
  figure:
    width: 10
    height: 8
    dpi: 300
    format: "png" # or "pdf", "svg"

  # Color palettes
  colors:
    condition: "Set1" # or specify custom colors
    batch: "Set3"
    continuous: "viridis"

  # Plot types to generate
  plots:
    qc_metrics: true
    umap_overview: true
    volcano_plot: true
    de_heatmap: true
    neighborhood_plot: true
    lemur_diagnostics: true

  # Plot-specific parameters
  volcano:
    label_top_genes: 20
    point_size: 0.8
    alpha: 0.6

  heatmap:
    top_genes: 50
    cluster_rows: true
    cluster_cols: true
    show_gene_names: true

# Output Options
output:
  # File formats
  save_formats:
    tables: ["csv", "xlsx"] # csv, xlsx, tsv
    plots: ["png", "pdf"] # png, pdf, svg

  # What to save
  save_objects:
    sce_filtered: true
    lemur_fit: true
    de_results: true
    embeddings: true
    workspace: true

  # Compression
  compression:
    use_compression: true
    method: "gzip" # gzip, bzip2

# Performance Settings
performance:
  # Parallel processing
  parallel:
    enable: true
    n_cores: 4 # or "auto" to detect

  # Memory management
  memory:
    use_hdf5: true
    chunk_size: 1000

  # Progress reporting
  verbose: true
  progress_bar: true

# Reproducibility
reproducibility:
  # Random seed for reproducible results
  seed: 42

  # Session info
  save_session_info: true

# Validation
validation:
  # Input validation
  check_metadata: true
  check_file_paths: true

  # Analysis validation
  check_convergence: true
  validate_results: true

# Custom Analysis Options
custom:
  # Gene sets of interest (optional)
  gene_sets_of_interest:
    complement: ["C1QA", "C1QB", "C1QC", "C3", "C4A", "C4B", "CFH"]
    neuroinflammation: ["TNF", "IL1B", "IL6", "NFKB1"]

  # Additional filtering (optional)
  exclude_cell_types: [] # cell types to exclude
  include_cell_types: [] # if specified, only include these

  # Custom QC thresholds per condition (optional)
  condition_specific_qc: false

# Advanced Options
advanced:
  # Debug mode
  debug: false

  # Intermediate file saving
  save_intermediate: false

  # Custom R code injection points
  custom_preprocessing: null
  custom_postprocessing: null

  # Error handling
  continue_on_error: false

  # Logging
  log_level: "INFO" # DEBUG, INFO, WARNING, ERROR
  log_file: "lemur_analysis.log"
